#!/bin/bash

##
## Render the unit slides
##

shopt -s nullglob

# First, do some cleanup to start fresh.
# Remove all unit slides in tex and pdf and all
# generated figures (pdf and png)
for f in U??-*.pdf
do
  rm -f "$f"
done
for f in U??-*.tex
do
  rm -f "$f"
done
for f in FIGS/U??-*.pdf
do
  rm -f "$f"
done
for f in FIGS/U??-*.png
do
  rm -f "$f"
done
for f in CODE/U??-*.R
do
  rm -f "$f"
done

# Now knit the slides
for f in U??-*.Rnw
do
  Rscript -e "library(knitr); knit('$f')"
done

# Compile the resulting LaTeX files
for f in U??-*.tex 
do
    # We need to run pdflatex three times to get cross-references and TOC right
    pdflatex -interaction=nonstopmode "$f"
    pdflatex -interaction=nonstopmode "$f"
    pdflatex -interaction=nonstopmode "$f"
done

# Clean up auxiliary files
find . -maxdepth 1 \( -name "*.aux" -o -name "*-concordance.tex" -o -name "*.fdb_latexmk" -o -name "*.fls" -o -name "*.idx" -o -name "*.ilg" -o -name "*.ind" -o -name "*.log" -o -name "*.nav" -o -name "*.out" -o -name "*.snm" -o -name "*.synctex.gz" -o -name "*.toc" -o -name "*.vrb" \) -delete
