#!/bin/bash

# Render the slides
# Do a web render (will not work in the absence of a
# web connection)
# Does pull and push, so beware..

npx @marp-team/marp-cli@latest  --bespoke.progress --html math-2740-slides-*.md
for f in math-2740-slides-*.Rnw
do
  Rscript -e "library(knitr); knit('$f.Rnw')"
  pdflatex $f.tex
done


npx @marp-team/marp-cli@latest  --bespoke.progress --html MATH2740-slides-*.md
for f in MATH2740-slides-*.tex 
do
    # We need to run pdflatex twice to get the TOC right
    pdflatex $f
    pdflatex $f
done
for f in MATH2740-slides-*.ipynb
do
    jupyter nbconvert --execute --to html $f
done
rm *.aux *.fdb_latexmk *.fls *.idx *.ilg *.ind *.log *.nav *.out *.snm *.toc
git pull
git commit -a -m "Update the slides"
git push
