#!/bin/bash

# Render the lectures and copy them where they need 
# to be (/docs in the repo)
# Do a local render (might not be most recent version
# of marp)
# Does pull and push, so beware..


npx marp  --html MATH2740-slides-*.md
for f in MATH2740-slides-*.tex 
do
    # We need to run pdflatex twice to get the TOC right
    pdflatex $f
    pdflatex $f
done
for f in MATH2740-slides-*.ipynb
do
    jupyter nbconvert --execute --to html $f
done
rm *.aux *.fdb_latexmk *.fls *.idx *.ilg *.ind *.log *.nav *.out *.snm *.toc
git pull
git commit -a -m "Update the slides and assignments"
git push
