#!/bin/bash

##
## Render the lectures
##

# First, do some cleanup to start fresh.
# Remove all lecture slides in pdf and all
# generated figures (pdf and png)
for f in L??-*.pdf
do
  rm $f
done
for f in FIGS/L??-*.pdf
do
  rm $f
done
for f in FIGS/L??-*.png
do
  rm $f
done

# Now knit the slides
for f in L??-*.Rnw
do
  Rscript -e "library(knitr); knit('$f')"
done

# Compile the resulting LaTeX files
for f in L??-*.tex 
do
    # We need to run pdflatex three times to get cross-references and TOC right
    pdflatex -interaction=nonstopmode $f
    pdflatex -interaction=nonstopmode $f
    pdflatex -interaction=nonstopmode $f
done

# Clean up auxiliary files
find . -maxdepth 1 \( -name "*.aux" -o -name "*-concordance.tex" -o -name "*.fdb_latexmk" -o -name "*.fls" -o -name "*.idx" -o -name "*.ilg" -o -name "*.ind" -o -name "*.log" -o -name "*.nav" -o -name "*.out" -o -name "*.snm" -o -name "*.synctex.gz" -o -name "*.toc" -o -name "*.vrb" \) -delete
