#!/bin/bash

# Render the slides
# Do a web render (will not work in the absence of a
# web connection)
# Does pull and push, so beware..

npx @marp-team/marp-cli@latest  --bespoke.progress --html MATH2740-slides-*.md
for f in MATH2740-slides-*.tex 
do 
    pdflatex $f
done
for f in MATH2740-slides-*.ipynb
do
    jupyter nbconvert --execute --to html $f
done
rm *.aux *.fdb_latexmk *.fls *.idx *.ilg *.ind *.log *.nav *.out *.snm *.toc
git pull
git commit -a -m "Update the slides"
git push
