\documentclass[aspectratio=169]{beamer}

% Set lecture number for later use
<<set-lecture-number,echo=FALSE>>=
lecture_number = "01"
@

% Part common to all the lectures
\subtitle{MATH 2740 -- Mathematics of Data Science -- Lecture \Sexpr{lecture_number}}
\author{\texorpdfstring{Julien Arino\newline\url{julien.arino@umanitoba.ca}}{Julien Arino}}
\institute{Department of Mathematics @ University of Manitoba}
\date{Fall 202X}

% Title of the lecture
\title{Presentation of the course and setting up R}

<<set-options,echo=FALSE,warning=FALSE,message=FALSE>>=
# Source the code common to all lectures
source("common-code.R")
@

<<set-slide-background,echo=FALSE,results='asis'>>=
# Are we plotting for a dark background? Setting is in common-code.R, but
# cat command must run here.
cat(input_setup)
@

\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% TITLE AND OUTLINE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\titlepagewithfigure{FIGS-slides-admin/a_robot_looking_at_a_desolate_tree_in_the_style_of_Magritte.png}
\outlinepage{FIGS-slides-admin/a_robot_looking_at_a_desolate_tree_in_the_style_of_Dali.png}


%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
% Some information
\section{General information about the course}
% The section page
\newSectionSlide{FIGS-slides-admin/a_robot_using_an_easel_to_paint_a_desolate_tree_in_the_style_of_HR_Giger.png}

\begin{frame}{Foreword}
\begin{itemize}
\item "Numerical dates" are in the form YYYY-MM-DD (e.g, these slides were compiled on \Sexpr{Sys.Date()})
\vfill
\item Times are 24h (HHMM)
\vfill
\item Units are SI
\end{itemize}
\vfill
In case you want to know, the slides in the course are \code{Rnw} compiled using \code{R}. All (including source code) are available on GitHub \href{https://github.com/julien-arino/math2740-of-data-science}{here}
\end{frame}

\begin{frame}{Getting in touch}
\begin{itemize}
\item \href{mailto:julien.arino@umanitoba.ca}{julien.arino@umanitoba.ca}
\vfill
\item Please use your \texttt{myumanitoba} email address. Use a tag such as \texttt{[MATH 2740]} in your subject line, if you want to be read..
\vfill
\item Word of warning: I am bad with email! I do answer questions after class or during office hours
\end{itemize}
\end{frame}

\begin{frame}{Office hours}
\begin{itemize}
\item Because of the ongoing renovation of Machray Hall, I am sharing an office with 8 other colleagues. Next door are offices shared by another 8 and 4 colleagues
\vfill
\item It is therefore \textbf{impossible} for me to see you in my office
\vfill
\item I have booked 238 St Paul's from 1430 to 1600 on Tuesday and Thursday for office hours
\vfill
Seeing you outside of office hours is impossible without ample warning, since I actually need to book a room
\end{itemize}
\end{frame}

\begin{frame}{Course website - UMLearn}
\begin{itemize}
\item All information about the course is posted on UMLearn
\vfill
\item It is \textbf{your responsibility} to check the UMLearn site regularly: \textit{Announcements} is how I normally communicate with you about the course
\vfill
\item (Remember to hit the link at the top of the page that says \textit{MATH-2740-A01 - Mathematics of Data Science}, sometimes UMLearn takes you directly to Content, which is not where Announcements are)
\vfill \boldred{Important --} I \textsc{\textbf{do not}} answer emails that ask about things easy to find on UMLearn
\end{itemize}
\end{frame}

\begin{frame}{Lectures}
\begin{itemize}
\item TR 1130-1245 in 200 Fletcher Argue
\vfill
\item Videos for the course as I taught it in 2021 are available as a \href{https://www.youtube.com/playlist?list=PLfRaznSpWo2vQAn1jVyueTuAiryDaxkH3}{YouTube playlist}. There is no guarantee that that the content will be the same this year, but there will be commonalities for sure
\end{itemize}
\end{frame}

\begin{frame}{Tutorials}
\begin{itemize}
\item In tutorials, you will review some of the mathematical content and work on computations
\vfill
\item Short (15 minutes) quizzes will be held
\end{itemize}
\vfill
\begin{center}
\begin{tabular}{lll}
\toprule
Section & Day and time & Location \\
\midrule
B01 & W 0830-0920 & 301 Biological Sciences \\
B02 & W 0930-1020 & 301 Biological Sciences \\
B03 & W 1130-1220 & 301 Biological Sciences \\
B04 & W 0830-0920 & 505 Tier \\
\bottomrule
\end{tabular}
\end{center}
\end{frame}

\begin{frame}{Evaluation}
\begin{itemize}
\item 1 final examination during the Examination period (\textbf{35\%})
\vfill
\item 1 midterm on Monday 27 October 1900--2100 (\textbf{25\%})
\vfill
\item 4 quizzes during tutorials (\textbf{5\%} each for a total \textbf{20\%})
\vfill
\item 4 assignments (\textbf{5\%} each for a total \textbf{20\%})
\end{itemize}
\end{frame}

\begin{frame}{Quizzes}
\bbullet Held during tutorials
\vfill
\bbullet 15 minutes long 
\vfill
\bbullet One of the timeslots (0830, 0930 or 1130) writes on a given week
\vfill
\bbullet Tests your capacity to do simple proofs or remember definitions or results
\end{frame}

\begin{frame}{Assignment schedule}
\begin{center}
\begin{tabular}{ccc}
\toprule
Assignment number & Handed out & Due \\
\midrule
Assignment 1 & 19 September & 3 October \\
Assignment 2 & 10 October & 24 October\\
Assignment 3 & 31 October & 21 November \\
Assignment 4 & 21 November & 5 December \\
\bottomrule
\end{tabular}
\end{center}
\end{frame}

\begin{frame}{Assignments}
\begin{itemize}
\item Assignments will be computational
\vfill
\item \boldred{No tolerance for late assignments} and no make-up for missed assignments: any assignment not returned by the deadline will result in a mark of \boldred{zero}
\vfill
\item Computer assignments will need to be handed back in \texttt{R} (Python $\Rightarrow$ 0)
\end{itemize}
\end{frame}

\begin{frame}{CS students (in particular), beware!}
\begin{itemize}
\item Use Rmarkdown to generate a \boldred{notebook}. See more on this in Lecture 02
\vfill
\item Notebooks mix formatted text and code. They are executable and should be submitted as source, not as pdf or html or whatever. Only files in .Rmd are accepted
\vfill
\item Notebooks are not straight code. Submitting straight R code in a notebook with commented code $\Rightarrow$ 0)
\end{itemize}
\end{frame}

\begin{frame}{Returning assignments}
\begin{itemize}
\item Assignments go to UMLearn
    \begin{itemize}
    \item \texttt{R} language only (Python $\Rightarrow$ 0)
    \item Needs to be RMarkdown file (.Rmd)
    \item Single file
    \item Can submit several times but only the latest file will be used
    \end{itemize}
    \vfill
    \item Your code must run! It must also use the "Be friendly to others" method in \href{https://julien-arino.github.io/R-for-modellers/SLIDES/vignette-03-installing-using-packages.html\#/be-friendly-to-others}{these slides}
\end{itemize}
\end{frame}

\begin{frame}{In assignments/quizzes/midterm/final..}
\begin{itemize}
\item Explain what you are doing
\vfill
\item Math or code without explanation will lose marks
\end{itemize}
\end{frame}

\begin{frame}{Self-declaration of absences}
\begin{itemize}
\item You can self-declare an absence of less than 120 hours (5 days)
\vfill
\item Self-declarations are intended for occasional and unforeseen circumstances $\implies$ I \textbf{will not accept more than one} during the term
\vfill
\item Self-declarations must be filed less than 48 hours after the event you are using it for
\vfill
\item There is no make up for anything missed because of a self-declared absence: any percentage will be moved to the final examination
\vfill
\item See the details and the form here (\href{https://umanitoba.ca/student-supports/academic-supports/student-advocacy/self-declaration-policy-students}{link}). You \textbf{must} use the form on that page to self-declare your absence
\end{itemize}
\end{frame}

\begin{frame}{Academic dishonesty}
\begin{itemize}
\item Feel free to discuss work with others, but solutions must be your own!
\vfill
\item Markers will be on the lookout for this
\vfill
\item Paraphrasing my computer code = academic dishonesty !
\vfill
\item \href{https://stackoverflow.com/}{stack overflow} is a fantastic resource but if you use a solution from there, cite it (in a notebook, that's easy)
\vfill
\item ChatGPT, GitHub Copilot, etc. are wonderful tools, but you must use them wisely. Pure unaltered LLM production $\Rightarrow$ AD
\vfill
\item FYI: my PhD student who is marking your computer code and some of your math has been working with LLMs for quite a while now. Their LLM detection radar is finely tuned
\end{itemize}
\end{frame}

%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\section{Setting things up for the course}
% The section page
\newSectionSlide{FIGS-slides-admin/Gemini_Generated_Image_4vlmzf4vlmzf4vlm.jpeg}

\begin{frame}{We will be programming quite a bit}
As already indicated, Data Science is a very hands-on discipline. We will be programming quite a bit in this course
\vfill
Indeed, we can work out some of the examples "by hand", but to make things interesting, we typically need to consider larger examples where hand calculations are not pleasant or not even feasible
\end{frame}

\begin{frame}{R versus Python}
Slightly different take on life :)
\vfill
In short: \texttt{Python} is more CS, \texttt{R} is more Stats/Math
\vfill
Both are good languages for data science
\vfill
In this course, assignments \textbf{must} use \texttt{R}
\end{frame}

\begin{frame}{R was originally for stats but is now more}
\begin{itemize}
\item Open source version of S
\vfill
\item Appeared in 1993
\vfill
\item Now version 4.5
\vfill
\item Uses a lot of C and Fortran code. E.g., \texttt{deSolve}:
\begin{quote}
The functions provide an interface to the FORTRAN functions 'lsoda', 'lsodar', 'lsode', 'lsodes' of the 'ODEPACK' collection, to the FORTRAN functions 'dvode', 'zvode' and 'daspk' and a C-implementation of solvers of the 'Runge-Kutta' family with fixed or variable time steps
\end{quote}
\vfill
\item Very active community on the web, easy to find solutions \end{itemize}
\end{frame}

\begin{frame}{Getting your computer ready for the course}
All computer coding is in \texttt{R}; assignments also need to be returned in \texttt{R}
\vfill
$\implies$ you need to find a way to run \texttt{R}. Next slide: some methods, from the easiest to the most challenging.
\vfill
Note that all options described below are Open Source (completely free)
\end{frame}

\begin{frame}{In short...}
\begin{itemize}
\item Terminal version, not very friendly
\vfill
\item Nicer terminal: \href{https://github.com/randy3k/radian}{radian}
\vfill
\item Execute R scripts by using \texttt{Rscript name\_of\_script.R}. Useful to run code in \texttt{cron}, for instance
\vfill
\item Use IDEs:
    \begin{itemize}
    \item \href{https://www.rstudio.com/products/rstudio/}{RStudio} has become the reference
    \item \href{https://invent.kde.org/education/rkward}{RKWard} is useful if you are for instance using an ARM processor (Raspberry Pi, some Chromebooks..)
    \end{itemize}
\vfill
\item Integrate into jupyter notebooks
\end{itemize}
\end{frame}

\begin{frame}{Install R and RStudio}
This is probably the best option if you intend to go a little further than what we will do in the course. \texttt{R} is available on most platforms, while \texttt{RStudio} is available on most platforms except for Linux ARM devices (but can be compiled there)
\vfill
Visit \href{https://www.r-project.org/}{https://www.r-project.org/}
\vfill
Choose your version: Windows or Mac. Under Linux, you can install directly from your package manager (e.g., \texttt{sudo apt install R-base} for Debian-based distros)
\vfill
To install RStudio, see \href{https://www.rstudio.com/products/rstudio/}{here}
\end{frame}

\begin{frame}{Going further}
\begin{itemize}
\item \href{https://www.rstudio.com/products/rstudio/\#rstudio-server}{RStudio server}: run RStudio on a Linux server and connect via a web interface
\vfill
\item Shiny: easily create an interactive web site running R code
\vfill
\item \href{https://www.rstudio.com/products/shiny/shiny-server/}{Shiny server}: run Shiny apps on a Linux server
\vfill
\item Rmarkdown: markdown that incorporates R commands. Useful for generating reports in html or pdf, can make slides as well..
\vfill
\item Sweave/knitr: \LaTeX\ incorporating R commands. Useful for generating reports. Not used as much as Rmarkdown these days (but used for these slides)
\end{itemize}
\end{frame}


%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%
\section{(Super brief) Introduction to programming in R}
% The section page
\newSectionSlide{FIGS-slides-admin/Gemini_Generated_Image_dzsfcndzsfcndzsf.jpeg}

\begin{frame}{R is a scripted language}
\begin{itemize}
\item Interactive
\vfill
\item Allows you to work in real time
\vfill
    \begin{itemize}
    \item Be careful: what is in memory might involve steps not written down in a script
    \vfill
    \item If you want to reproduce your steps, it is good to write all the steps down in a script and to test from time to time running using \texttt{Rscript}: this will ensure that all that is required to run is indeed loaded to memory when it needs to, i.e., that it is not already there..
    \end{itemize}
\end{itemize}
\end{frame}


\begin{frame}{Assignment}
Two ways:

<<assignment1, eval=FALSE>>=
X <- 10
@

or

<<assignment2, eval=FALSE>>=
X = 10
@

First version is preferred by R purists.. I don't really care
\end{frame}

\begin{frame}[fragile]{Lists}
A very useful data structure, quite flexible and versatile. Empty list: \texttt{L <- list()}. Convenient for things like parameters. For instance

<<lists_example1, eval=FALSE>>=
L <- list()
L$a <- 10
L$b <- 3
L[["another_name"]] <- "Plouf plouf"
@

<<lists_example2, eval=FALSE>>=
> L[1]
$a
[1] 10
> L[[2]]
[1] 3
> L$a
[1] 10
> L[["b"]]
[1] 3
> L$another_name
[1] "Plouf plouf"
@
\end{frame}

\begin{frame}[fragile]{Vectors}
<<vectors_example, eval=FALSE>>=
x = 1:10
y <- c(x, 12)
> y
 [1]  1  2  3  4  5  6  7  8  9 10 12
z = c("red", "blue")
> z
[1] "red"  "blue"
z = c(z, 1)
> z
[1] "red"  "blue" "1"
@

Note that in \texttt{z}, since the first two entries are characters, the added entry is also a character. Contrary to lists, vectors have all entries of the same type
\end{frame}

\begin{frame}[fragile]{Matrices}
Matrix (or vector) of zeros
<<matrix_zeros, eval=FALSE>>=
A <- mat.or.vec(nr = 2, nc = 3)
@

Matrix with prescribed entries

<<matrix_prescribed, eval=FALSE>>=
B <- matrix(c(1,2,3,4), nr = 2, nc = 2)
> B
     [,1] [,2]
[1,]    1    3
[2,]    2    4
C <- matrix(c(1,2,3,4), nr = 2, nc = 2, byrow = TRUE)
> C
     [,1] [,2]
[1,]    1    2
[2,]    3    4
@

Remark that here and elsewhere, naming the arguments (e.g., \texttt{nr = 2}) allows to use arguments in any order
\end{frame}

\begin{frame}{Matrix operations}
Probably the biggest annoyance in R compared to other languages
\vfill
\begin{itemize}
\item The notation \texttt{A*B} is the \textit{Hadamard product} $A\circ B$ (what would be denoted \texttt{A.*B} in matlab), not the standard matrix multiplication
\vfill
\item Matrix multiplication is written \texttt{A \%*\% B}
\end{itemize}
\end{frame}

\begin{frame}[fragile]{Vector operations}
Vector addition is also frustrating. Say you write \texttt{x=1:10}, i.e., make the vector
<<vector_ops1, eval=FALSE>>=
> x
 [1]  1  2  3  4  5  6  7  8  9 10
@

Then \texttt{x+1} gives
<<vector_ops2, eval=FALSE>>=
> x+1
 [1]  2  3  4  5  6  7  8  9 10 11
@

i.e., adds 1 to all entries in the vector
\vfill
Beware of this in particular when addressing sets of indices in lists, vectors or matrices
\end{frame}

\begin{frame}[fragile]{Flow control}
<<flow_control, eval=FALSE>>=
if (condition is true) {
  list of stuff to do
}
@

Even if \texttt{list of stuff to do} is a single instruction, best to use curly braces

<<flow_control_extended, eval=FALSE>>=
if (condition is true) {
  list of stuff to do
} else if (another condition) {
  ...
} else {
  ...
}
@
\end{frame}

\begin{frame}[fragile]{For loops}
\texttt{for} applies to lists or vectors

<<for_loops, eval=FALSE>>=
for (i in 1:10) {
  something using integer i
}
for (j in c(1,3,4)) {
  something using integer j
}
for (n in c("truc", "muche", "chose")) {
  something using string n
}
for (m in list("truc", "muche", "chose", 1, 2)) {
  something using string n or integer n, depending
}
@
\end{frame}

\begin{frame}[fragile]{lapply}
Very useful function (a few others in the same spirit: \texttt{sapply}, \texttt{vapply}, \texttt{mapply})

Applies a function to each entry in a list/vector/matrix. Because there is a parallel version (\texttt{parLapply}) that we will see later, worth learning

<<lapply_example1, eval=FALSE>>=
l = list()
for (i in 1:10) {
        l[[i]] = runif(i)
}
lapply(X = l, FUN = mean)
@

or, to make a vector

<<lapply_example2, eval=FALSE>>=
unlist(lapply(X = l, FUN = mean))
@

or

<<lapply_example3, eval=FALSE>>=
sapply(X = l, FUN = mean)
@
\end{frame}

\begin{frame}[fragile]{``Advanced'' lapply}
Can ``pick up'' nontrivial list entries

<<lapply_advanced, eval=FALSE>>=
l = list()
for (i in 1:10) {
        l[[i]] = list()
        l[[i]]$a = runif(i)
        l[[i]]$b = runif(2*i)
}
sapply(X = l, FUN = function(x) length(x$b))
@

gives

<<lapply_advanced_result, eval=FALSE>>=
[1]  2  4  6  8 10 12 14 16 18 20
@

Just recall: the argument to the function you define is a list entry (\texttt{l[[1]]}, \texttt{l[[2]]}, etc., here)
\end{frame}

\begin{frame}[fragile]{Avoid parameter variation loops with expand.grid}
<<expand_grid, eval=FALSE>>=
# Suppose we want to vary 3 parameters
variations = list(
    p1 = seq(1, 10, length.out = 10),
    p2 = seq(0, 1, length.out = 10),
    p3 = seq(-1, 1, length.out = 10)
)

# Create the list
tmp = expand.grid(variations)
PARAMS = list()
for (i in 1:dim(tmp)[1]) {
    PARAMS[[i]] = list()
    for (k in 1:length(variations)) {
        PARAMS[[i]][[names(variations)[k]]] = tmp[i, k]     
    }
}
@

There is still a loop, but you can split this list, use it on different machines, etc. And can use \texttt{parLapply}
\end{frame}

\end{document}
