\documentclass[aspectratio=169]{beamer}

% Set lecture number for later use
<<set-lecture-number,echo=FALSE>>=
lecture_number = "14"
@

% Part common to all the lectures
\subtitle{MATH 2740 -- Mathematics of Data Science -- Lecture \Sexpr{lecture_number}}
\author{\texorpdfstring{Julien Arino\newline\url{julien.arino@umanitoba.ca}}{Julien Arino}}
\institute{Department of Mathematics @ University of Manitoba}
\date{Fall 202X}

% Title of the lecture
\title{Matrix methods -- Absorbing Markov chains}

<<set-options,echo=FALSE,warning=FALSE,message=FALSE>>=
# Source the code common to all lectures
source("common-code.R")
@

<<set-slide-background,echo=FALSE,results='asis'>>=
# Are we plotting for a dark background? Setting is in common-code.R, but
# cat command must run here.
cat(input_setup)
@

<<setup, include=FALSE>>=
# Set global chunk options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
@

\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% TITLE AND OUTLINE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\titlepagewithfigure{FIGS-slides-admin/Gemini_Generated_Image_Kiki-as-king.png}
\outlinepage{FIGS-slides-admin/Gemini_Generated_Image_Kiki-as-devil.png}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Absorbing Markov chains}
\newSectionSlide{FIGS-slides-admin/Gemini_Generated_Image_Kiki-bof.png}

\begin{frame}{Modifying the breeding experiment}
    We modify the setup in Lecture 13 by now repeatedly mating a female offspring with an orange male ($X^O Y$).
    \vfill
    The state of the chain is the genotype of the female offspring from the previous generation
    \vfill
    There are 3 possible states for the female offspring:
    \begin{itemize}
        \item $S_1$: $X^O X^O$ (orange female)
        \item $S_2$: $X^o X^o$ (black female)
        \item $S_3$: $X^O X^o$ (tortoiseshell female)
    \end{itemize}
\end{frame}

\begin{frame}{State 1 -- orange female ($X^O X^O$)}
    Current state is $S_1$. Mate this $X^O X^O$ female with the $X^O Y$ male
    \vfill
    \begin{center}
          \renewcommand{\arraystretch}{1.5}
      \begin{tabular}{c c | c | c |}
      \multicolumn{2}{c}{} & \multicolumn{1}{c}{$X^O$} & \multicolumn{1}{c}{$Y$} \\ \cline{3-4}
      \multirow{2}{*}{\rotatebox{90}{Mother}} & $X^O$ & \cellcolor{punnettorange}$X^O X^O$ ($S_1$) & \cellcolor{punnettorange}Orange male \\ \cline{2-4}
      & $X^O$ & \cellcolor{punnettorange}$X^O X^O$ ($S_1$) & \cellcolor{punnettorange}Orange male \\ \cline{2-4}
      \end{tabular}
    \end{center}

    \vfill
    The female offspring are:
    \begin{itemize}
        \item 100\% $X^O X^O$ (state $S_1$)
    \end{itemize}
\end{frame}

\begin{frame}{State 2 -- black female ($X^o X^o$)}
    Current state is $S_2$. Mate this $X^o X^o$ female with an $X^O Y$ male
    \vfill
    \begin{center}
          \renewcommand{\arraystretch}{1.5}
      \begin{tabular}{c c | c | c |}
      \multicolumn{2}{c}{} & \multicolumn{1}{c}{$X^O$} & \multicolumn{1}{c}{$Y$} \\ \cline{3-4}
      \multirow{2}{*}{\rotatebox{90}{Mother}} & $X^o$ & \cellcolor{punnetttortie}$X^O X^o$ ($S_1$) & \cellcolor{punnettblack}Black male \\ \cline{2-4}
      & $X^o$ & \cellcolor{punnetttortie}$X^O X^o$ ($S_3$) & \cellcolor{punnettblack}Black male \\ \cline{2-4}
      \end{tabular}
    \end{center}
    \vfill
    The female offspring are:
    \begin{itemize}
        \item 100\% $X^O X^o$ (State $S_3$) $\implies \IP(S_2 \to S_3) = 1$
    \end{itemize}
\end{frame}

\begin{frame}{State 3 -- tortoiseshell female ($X^O X^o$)}
    Current state is $S_3$. Mate this $X^O X^o$ female with the $X^O Y$ male
    \vfill
    \begin{center}
          \renewcommand{\arraystretch}{1.5}
      \begin{tabular}{c c | c | c |}
      \multicolumn{2}{c}{} & \multicolumn{1}{c}{$X^O$} & \multicolumn{1}{c}{$Y$} \\ \cline{3-4}
      \multirow{2}{*}{\rotatebox{90}{Mother}} & $X^O$ & \cellcolor{punnettorange}$X^O X^O$ ($S_1$) & \cellcolor{punnettorange}Orange male \\ \cline{2-4}
      & $X^o$ & \cellcolor{punnetttortie}$X^O X^o$ ($S_3$) & \cellcolor{punnettblack}Black male \\ \cline{2-4}
      \end{tabular}
    \end{center}
    \vfill
    The female offspring have a 50/50 chance:
    \begin{itemize}
        \item 50\% $X^O X^O$ (State $S_1$) $\implies \IP(S_3 \to S_1) = 1/2$
        \item 50\% $X^O X^o$ (State $S_3$) $\implies \IP(S_3 \to S_3) = 1/2$
    \end{itemize}
\end{frame}

\begin{frame}{Summary of the chain}
    \[
    P = \begin{pmatrix}
    1 & 0 & 1/2 \\
    0 & 0 & 0 \\
    0 & 1 & 1/2
    \end{pmatrix}
    \]
    
    \vfill
\begin{center}
\begin{tikzpicture}[
    ->, % All paths have arrows
    >=Latex, % Use the nicer Latex arrow tip
    node distance=2.5cm, % Distance between nodes
    every path/.style={thick}
]
    \node[state,fill=punnettorange] (S1) at (0, 2) {$X^OX^O$};
    \node[state,fill=punnettblack] (S2) at (-2, 0) {$X^oX^o$};
    \node[state,fill=punnetttortie] (S3) at (2, 0) {$X^OX^o$};
    \path (S1) edge [loop left] node[left] {$1$} (S1);
    \path (S2) edge node[above] {$1$} (S3);
    \path (S3) edge [loop right] node[right] {$0.5$} (S3);
    \path (S3) edge node[sloped,below] {$0.5$} (S1);
\end{tikzpicture}
\end{center}    
\end{frame}



\begin{frame}{Absorbing Markov chains}
\begin{definition}[Absorbing state]
A state $S_i$ in a Markov chain is \textbf{absorbing} if whenever it occurs on the $t^{th}$ generation of the experiment, it then occurs on every subsequent step. In other words, $S_i$ is absorbing if $p_{ii}=1$ and $p_{ij}=0$ for $i\neq j$
\end{definition}
\vfill
\begin{definition}[Absorbing chain]
A Markov chain is \textbf{absorbing} if it has at least one absorbing state, and if from every state it is possible to go to an absorbing state.
In an absorbing Markov chain, a state that is not absorbing is called \textbf{transient}
\end{definition}
\end{frame}


\begin{frame}{Questions about absorbing chains}
Suppose we have a chain like the following
\begin{center}
\begin{tikzpicture}
	[inner sep=2mm,
	place/.style={circle,fill=black!10,thick,minimum size=1cm}]
	\node [place] (1) {$S_1$};
	\node [place] (2) [right=of 1] {$S_2$};
	\node [place] (3) [right=of 2] {$S_3$};
	\node [place] (4) [right=of 3] {$S_4$};
	\draw[->] (1) to [loop above] (1);
	\draw[->] (2) to [loop above] (2);
	\draw[->] (3) to [loop above] (3);
	\draw[->] (4) to [loop above] (4);
	\draw[->] (2) to (1);
	\draw[->] (2) to [bend left] (3);
	\draw[->] (3) to [bend left] (2);
	\draw[->] (3) to (4);
\end{tikzpicture}
\end{center}
\vfill
\begin{enumerate}
\item Does the process eventually reach an absorbing state?
\item What is the average number of steps spent in a transient state, if starting in a transient state?
\item What is the average number of steps before entering an absorbing state?
\item What is the probability of being absorbed by a given absorbing state, when there are more than one, when starting in a given transient state?
\end{enumerate}
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Analysing absorbing Markov chains}
\newSectionSlide{FIGS-slides-admin/Gemini_Generated_Image_Kiki-bof.png}

\begin{frame}
The answer to the first question (``Does the process eventually reach an absorbing state?'') is given by the following result
\vfill
\begin{theorem}
In an absorbing Markov chain, the probability of reaching an absorbing state is 1
\end{theorem}
\end{frame}

\begin{frame}
To answer the other questions, write the transition matrix in \textbf{standard} form
\vfill
For an absorbing chain with $k$ absorbing states and $r-k$ transient states, write transition matrix as
\[
P=\begin{pmatrix}
\mathbb{I}_k & R \\
\b0 & Q
\end{pmatrix}
\]
with following meaning
\begin{center}\footnotesize
\begin{tabular}{ccc}
& Absorbing states & Transient states \\
Absorbing states & $\mathbb{I}_k$ & $R$ \\
Transient states & $\b0$ & $Q$
\end{tabular}
\end{center}
with $\mathbb{I}_k$ the $k\times k$ identity matrix, $\mathbf{0}$ an $(r-k)\times k$ matrix of zeros, $R$ an $k\times (r-k)$ matrix and $Q$ an $(r-k)\times(r-k)$ matrix.
The matrix $\mathbb{I}_{r-k}-Q$ is invertible. Let
\begin{itemize}
\item $N=(\mathbb{I}_{r-k}-Q)^{-1}$ the \textbf{fundamental matrix} of the MC
\item $T_i$ sum of the entries on column $i$ of $N$
\item $B=RN$
\end{itemize}
\end{frame}

\begin{frame}
Answers to our remaining questions:
\vfill
\begin{enumerate}
\setcounter{enumi}{1}
\item $N_{ij}$ average number of times the process is in the $i$th transient state if it starts in the $j$th transient state
\vfill
\item $T_i$ average number of steps before the process enters an absorbing state if it starts in the $i$th transient state
\vfill
\item $B_{ij}$ probability of eventually entering the $i$th absorbing state if the process starts in the $j$th transient state
\end{enumerate}
\vfill
\end{frame}

\begin{frame}{Back to the genetic example}
The matrix is already in standard form
\[
P=
\begin{pmatrix}
1 & 0 & 1/2 \\
0 & 0 & 0 \\
0 & 1 & 1/2
\end{pmatrix}
=\begin{pmatrix}
\mathbb{I}_1 & R \\
\b0 & Q
\end{pmatrix}
\]
with $\mathbb{I}_1=1$, $\mathbf{0}=(0\;\; 0)^T$ and
\[
R=\begin{pmatrix}
0 & 1/2
\end{pmatrix}
\qquad
Q=\begin{pmatrix}
0 & 0\\
0 & 1/2
\end{pmatrix}
\]
We have
\[
\mathbb{I}_2-Q=\begin{pmatrix}
1 & 0 \\
0 & 1
\end{pmatrix}
-\begin{pmatrix}
0 & 0\\
0 & 1/2
\end{pmatrix}
=\begin{pmatrix}
1 & 0\\
0 & 1/2
\end{pmatrix}
\]
so the fundamental matrix is
\[
N=(\mathbb{I}_2-Q)^{-1}=
\begin{pmatrix}
1 & 0 \\
0 & 2
\end{pmatrix}
\]
\end{frame}


\begin{frame}{Summary about absorption}
Fundamental matrix, whose $(i,j)$ entry is the average number of visits to the $i$th transient state if it starts in the $j$th transient state
\[
N=
\begin{pmatrix}
1 & 0 \\
0 & 2
\end{pmatrix}
\]
\vfill
Average number of steps before absorption (i.e., only orange females) if we start in a transient state is
\[
T=\nbOne^TN=(1,2)
\]
\vfill
Probability of eventually entering the $i$th absorbing state if we start in the $j$th transient state
\[
B=RN=
\begin{pmatrix}
	0 & 1/2
\end{pmatrix}
\begin{pmatrix}
1 & 0 \\
0 & 2
\end{pmatrix}
=
\begin{pmatrix}
0 & 1
\end{pmatrix}
\]
\end{frame}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\Ssection{Numerics}{FIGS-slides-admin/Gemini_Generated_Image_Kiki-bof.png}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\Ssubsection{Regular MC example}{FIGS-slides-admin/Gemini_Generated_Image_Kiki-not-so-majestic.png}

<<>>=
# Library
library(markovchain)
# Make the transition matrix
P_reg = matrix(c(0.5, 0, 0.25,
                 0, 0.5, 0.25,
                 0.5, 0.5, 0.5),
               nr = 3, byrow = TRUE)
# Library: markovchain
mc_reg <- new("markovchain",
              states = sprintf("S_%d", 1:3),
              transitionMatrix = t(P_reg),
              name = "orange_reg")
@

\begin{frame}[fragile]
<<>>=
summary(mc_reg)
@
\end{frame}

\begin{frame}[fragile]
\frametitle{The equilibrium distribution}
<<>>=
steadyStates(mc_reg)
@
\end{frame}
  
\begin{frame}[fragile]
\frametitle{Showing a realisation}
<<DTMC-random-walk-regular, >>=
library(DTMCPack)
IC = rep(0, dim(P_reg)[1])
IC[1] = 1
sol = DTMC(t(P_reg), IC, 41, trace=TRUE)
@
\end{frame}

\maxFrameImage{\Sexpr{fig_chunk('DTMC-random-walk-regular', 'pdf')}}
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\Ssubsection{Absorbing MC example}{FIGS-slides-admin/Gemini_Generated_Image_Kiki-not-so-majestic.png}

\begin{frame}[fragile]\frametitle{The absorbing version}
<<>>=
P_abs = matrix(c(1, 0, 0.5,
                 0, 0, 0,
                 0, 1, 0.5),
               nr = 3, byrow = TRUE)
mc_abs <- new("markovchain", 
              states = sprintf("S_%d", 1:3),
              transitionMatrix = t(P_abs),
              name = "orange_abs")
@
\end{frame}
  
\begin{frame}[fragile]\frametitle{Show some info about the chain}
<<>>=
summary(mc_abs)
@
\end{frame}
  
\begin{frame}[fragile]\frametitle{Plotting the chain}
<<DTMC-random-walk-absorbing>>=
plot(mc_abs)
@
\end{frame}
  
\maxFrameImage{\Sexpr{fig_chunk('DTMC-random-walk-absorbing', 'pdf')}}
  
\begin{frame}[fragile]\frametitle{Showing a realisation}
<<DTMC-random-walk-absorbing-realisation>>=
IC = rep(0, dim(P_abs)[1])
IC[3] = 1
sol = DTMC(t(P_abs), IC, 10, trace=TRUE)
@
\end{frame}

\maxFrameImage{\Sexpr{fig_chunk('DTMC-random-walk-absorbing-realisation', 'pdf')}}

\begin{frame}\frametitle{Additional information about absorbing chains}
\code{canonicForm(mc\_abs)}
\vfill
\code{meanAbsorptionTime(mc\_abs)}
\vfill
\code{absorptionProbabilities(mc\_abs)}
\vfill
\code{hittingProbabilities(mc\_abs)}
\end{frame}

\begin{frame}[fragile]\frametitle{Canonical form}
<<>>=
canonicForm(mc_abs)
@
\end{frame}

\begin{frame}[fragile]\frametitle{Mean absorption time}
<<>>=
meanAbsorptionTime(mc_abs)
@
\end{frame}

\begin{frame}[fragile]\frametitle{Absorption probabilities}
<<>>=
absorptionProbabilities(mc_abs)
@
\end{frame}

\begin{frame}[fragile]\frametitle{Hitting probabilities}
<<>>=
hittingProbabilities(mc_abs)
@
\end{frame}

  


\end{document}
